"use client";
import {useEffect,useMemo,useState} from 'react';
import {Activity,AlertTriangle,CalendarDays,CheckCircle2,ChevronRight,Clock3,LogOut,RefreshCw,ShieldCheck,Sparkles,Timer,Users,Zap,TrendingUp} from 'lucide-react';

type Decision={state:string;stylistId:string;start:string;end:string;revenue:number;totalDelay:number;maxDelay:number;wait:number;affected:number;reason:string};

export default function Dashboard(){
 const[d,setD]=useState<any>(); const[svc,setSvc]=useState(''); const[dec,setDec]=useState<Decision|null>(null); const[candidates,setCandidates]=useState<Decision[]>([]); const[busy,setBusy]=useState(false); const[accepted,setAccepted]=useState(false); const[error,setError]=useState(''); const[stage,setStage]=useState(0);
 const load=()=>fetch('/api/dashboard',{credentials:'include'}).then(async r=>r.ok?setD(await r.json()):location.href='/login').catch(()=>setError('Could not load the live salon state.'));
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(!busy)return;setStage(0);const t=setInterval(()=>setStage(s=>Math.min(s+1,4)),260);return()=>clearInterval(t)},[busy]);
 const selected=useMemo(()=>d?.services?.find((s:any)=>s.id===svc),[d,svc]);
 const utilization=Math.min(96,Math.round((d?.appointments?.length||0)/Math.max(1,(d?.stylists?.length||1)*4)*100));
 if(!d)return <div className="loading"><div><div className="spinner"/><b>Loading SALORA command center…</b><span>Synchronizing live salon state</span></div></div>;
 async function sim(){if(!svc)return;setBusy(true);setError('');setAccepted(false);try{const r=await fetch('/api/walk-ins/simulate',{method:'POST',headers:{'content-type':'application/json'},credentials:'include',body:JSON.stringify({serviceId:svc,now:new Date().toISOString()})});const x=await r.json();if(!r.ok)throw Error(x.error);setDec(x.recommendation);setCandidates(x.candidates||[])}catch(e:any){setError(e.message||'Simulation failed.')}finally{setBusy(false)}}
 async function accept(){if(!dec)return;setBusy(true);setError('');try{const r=await fetch('/api/walk-ins/accept',{method:'POST',headers:{'content-type':'application/json','idempotency-key':crypto.randomUUID()},credentials:'include',body:JSON.stringify({serviceId:svc,stylistId:dec.stylistId,startAt:dec.start,decisionState:dec.state})});const x=await r.json();if(!r.ok)throw Error(x.error);setAccepted(true);setDec(null);setCandidates([]);await load()}catch(e:any){setError(e.message||'Acceptance failed. Please simulate again.')}finally{setBusy(false)}}
 async function logout(){await fetch('/api/auth/logout',{method:'POST',credentials:'include'});location.href='/'}
 const statusIcon=dec?.state==='ACCEPT'?<CheckCircle2/>:dec?.state==='WAIT'?<Timer/>:dec?.state==='ACCEPT_WITH_WARNING'?<AlertTriangle/>:<ShieldCheck/>;
 const stages=['Reading live schedule','Testing safe placements','Propagating downstream impact','Ranking opportunities','Building explanation'];
 return <main className="dash-v2"><aside className="sidebar-v2"><div><b className="brand white"><i/> SALORA</b><div className="side-label">COMMAND CENTER</div><nav><a className="side-active"><Activity/>Overview</a><a><CalendarDays/>Schedule</a><a><Users/>Customers</a></nav></div><div className="side-bottom"><div className="engine-status"><span className="status-dot"/><div><small>DECISION ENGINE</small><b>Operational</b></div></div><button onClick={logout}><LogOut/>Sign out</button></div></aside>
 <section className="dash-main"><header className="dash-header"><div><div className="eyebrow"><span className="live-pulse"/> TODAY · LIVE OPERATIONS</div><h1>Good morning.</h1><p>{d.salon.name} · {d.salon.timezone}</p></div><div className="head-actions"><span className="live-pill">● LIVE</span><button className="iconbtn" onClick={load} title="Refresh"><RefreshCw size={16}/></button></div></header>
 {error&&<div className="alert-v2"><AlertTriangle size={16}/>{error}</div>}{accepted&&<div className="success-v2"><CheckCircle2 size={16}/> Walk-in accepted and added to the live schedule.</div>}
 <div className="kpis-v2"><K icon={<CalendarDays/>} v={d.appointments.length} t="Appointments today" sub="Live schedule"/><K icon={<Users/>} v={d.stylists.length} t="Stylists active" sub="Ready now"/><K icon={<TrendingUp/>} v={`₹${(d.services?.reduce((s:any,x:any)=>s+Number(x.price_inr),0)||0).toLocaleString('en-IN')}`} t="Service value" sub="Available menu"/><K icon={<Activity/>} v={`${utilization}%`} t="Schedule pressure" sub="Live estimate"/></div>
 <div className="dashboard-grid-v2">
  <section className="schedule-v2 panel-v2"><div className="panel-title"><div><span>LIVE SCHEDULE</span><h2>Salon flow</h2></div><b>{d.appointments.length} entries</b></div><div className="flow-legend"><span><i className="legend-booked"/>Booked</span><span><i className="legend-open"/>Open capacity</span><span><i className="legend-sim"/>Simulation</span></div>{d.appointments.length?d.appointments.map((a:any,i:number)=><div className={`appt-v2 ${i===0?'first':''}`} key={a.id}><div className="time-node"><time>{new Date(a.scheduled_start).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</time><i/></div><div className="appt-card"><div><b>{a.customer||'Guest'}</b><span>{a.service} · {a.stylist}</span></div><label>{a.status}</label></div></div>):<div className="empty-v2"><CalendarDays size={22}/><b>No appointments in the visible window</b><span>Your salon is quiet. That is a good time to accept a walk-in.</span></div>}<div className="schedule-footer"><div><small>CAPACITY SIGNAL</small><strong><i className="signal-dot"/> Healthy</strong></div><div><small>OPEN WINDOWS</small><strong>2 detected</strong></div></div></section>
  <section className="engine-v2 panel-v2"><div className="engine-badge"><Sparkles size={13}/> WALK-IN DECISION ENGINE</div><h2>Should we say yes?</h2><p className="engine-copy-v2">Ask the what-if question before changing the real schedule.</p><div className="question-card"><small>WALK-IN REQUEST</small><select value={svc} onChange={e=>{setSvc(e.target.value);setDec(null);setCandidates([])}}><option value="">Choose a service…</option>{d.services.map((s:any)=><option key={s.id} value={s.id}>{s.name} · {s.duration_min} min · ₹{s.price_inr.toLocaleString('en-IN')}</option>)}</select>{selected&&<div className="service-meta"><span>{selected.duration_min} min</span><span>₹{selected.price_inr.toLocaleString('en-IN')}</span><span>{selected.buffer_min} min buffer</span></div>}<button className="simulate-btn" disabled={!svc||busy} onClick={sim}>{busy?<><span className="btn-spinner"/> Analyzing…</>:`Run what-if simulation`}<Sparkles size={16}/></button></div>
  {busy&&<div className="simulation-progress"><div className="progress-head"><span>SIMULATING LIVE SCHEDULE</span><b>{Math.min(100,stage*25+25)}%</b></div><div className="progress-bar"><i style={{width:`${Math.min(100,stage*25+25)}%`}}/></div><div className="stage-list">{stages.map((s,i)=><span className={i<=stage?'done':''} key={s}>{i<=stage?'✓':'○'} {s}</span>)}</div></div>}
  {dec&&!busy&&<div className={`decision-result ${dec.state.toLowerCase()}`}><div className="decision-head"><div className="decision-state">{statusIcon}<div><small>ENGINE OUTPUT</small><strong>{dec.state.replaceAll('_',' ')}</strong><span>{dec.reason}</span></div></div><div className="decision-pulse"/></div><div className="metrics-v2"><Metric v={`₹${dec.revenue.toLocaleString('en-IN')}`} t="Revenue opportunity"/><Metric v={`${Math.round(dec.maxDelay)} min`} t="Max delay"/><Metric v={`${Math.round(dec.wait)} min`} t="Customer wait"/></div><div className="impact-v2"><span><b>{dec.affected}</b> appointments affected</span><span><b>{Math.round(dec.totalDelay)}</b> total delay minutes</span></div><div className="whatif-caption"><Zap size={13}/> SALORA found a safe placement for this scenario.</div>{dec.state!=='RESCHEDULE'&&<button className="accept-btn" disabled={busy} onClick={accept}>Accept this walk-in <ChevronRight size={16}/></button>}</div>}
  {candidates.length>1&&<div className="alternatives-v2"><div className="alt-head"><span>OTHER SAFE PLACEMENTS</span><small>COMPARE</small></div>{candidates.slice(1,4).map((c,i)=><div className="alt-row" key={i}><span>{c.state.replaceAll('_',' ')}</span><b>{new Date(c.start).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</b><em>{Math.round(c.maxDelay)}m delay</em></div>)}</div>}
  </section>
 </div>
 <div className="bottom-strip"><div><span><Zap size={13}/> SALORA PULSE</span><b>Opportunity detection active</b></div><div className="pulse-bar"><i style={{width:`${Math.max(20,utilization)}%`}}/></div><span>{utilization}% pressure</span></div>
 </section></main>;
}
function K({icon,v,t,sub}:{icon:React.ReactNode;v:string|number;t:string;sub:string}){return <div className="kpi-v2"><div className="kpi-icon">{icon}</div><strong>{v}</strong><span>{t}</span><small>{sub}</small></div>}
function Metric({v,t}:{v:string;t:string}){return <div><strong>{v}</strong><span>{t}</span></div>}
