"use client";
import {useEffect,useMemo,useState} from 'react';
import {Activity,CalendarDays,ChevronRight,Clock3,LogOut,Plus,RefreshCw,Sparkles,Users,CheckCircle2,AlertTriangle,Timer,ShieldCheck} from 'lucide-react';

type Decision={state:string;stylistId:string;start:string;end:string;revenue:number;totalDelay:number;maxDelay:number;wait:number;affected:number;reason:string};
export default function Dashboard(){
 const[d,setD]=useState<any>(); const[svc,setSvc]=useState(''); const[dec,setDec]=useState<Decision|null>(null); const[candidates,setCandidates]=useState<Decision[]>([]); const[busy,setBusy]=useState(false); const[accepted,setAccepted]=useState(false); const[error,setError]=useState('');
 const load=()=>fetch('/api/dashboard',{credentials:'include'}).then(async r=>r.ok?setD(await r.json()):location.href='/login').catch(()=>setError('Could not load the live salon state.'));
 useEffect(()=>{load()},[]);
 const selected=useMemo(()=>d?.services?.find((s:any)=>s.id===svc),[d,svc]);
 if(!d)return <div className="loading"><div><div className="spinner"/><b>Loading SALORA command center…</b></div></div>;
 async function sim(){if(!svc)return;setBusy(true);setError('');setAccepted(false);try{const r=await fetch('/api/walk-ins/simulate',{method:'POST',headers:{'content-type':'application/json'},credentials:'include',body:JSON.stringify({serviceId:svc,now:new Date().toISOString()})});const x=await r.json();if(!r.ok)throw Error(x.error);setDec(x.recommendation);setCandidates(x.candidates||[])}catch(e:any){setError(e.message||'Simulation failed.')}finally{setBusy(false)}}
 async function accept(){if(!dec)return;setBusy(true);setError('');try{const r=await fetch('/api/walk-ins/accept',{method:'POST',headers:{'content-type':'application/json','idempotency-key':crypto.randomUUID()},credentials:'include',body:JSON.stringify({serviceId:svc,stylistId:dec.stylistId,startAt:dec.start,decisionState:dec.state})});const x=await r.json();if(!r.ok)throw Error(x.error);setAccepted(true);setDec(null);setCandidates([]);await load()}catch(e:any){setError(e.message||'Acceptance failed. Please simulate again.')}finally{setBusy(false)}}
 async function logout(){await fetch('/api/auth/logout',{method:'POST',credentials:'include'});location.href='/'}
 const statusIcon=dec?.state==='ACCEPT'?<CheckCircle2/>:dec?.state==='WAIT'?<Timer/>:dec?.state==='ACCEPT_WITH_WARNING'?<AlertTriangle/>:<ShieldCheck/>;
 return <main className="dash"><aside><b className="logo"><i/>SALORA</b><small>COMMAND CENTER</small><nav><a className="active"><Activity/>Overview</a><a><CalendarDays/>Schedule</a><a><Users/>Customers</a></nav><div className="side-note"><Sparkles size={14}/><span>Decision engine<br/><b>Operational</b></span></div><button onClick={logout}><LogOut/>Sign out</button></aside><section className="content">
  <header><div><small className="eyebrow">TODAY · LIVE OPERATIONS</small><h1>Good morning.</h1><p>{d.salon.name} · {d.salon.timezone}</p></div><div className="head-actions"><button className="iconbtn" onClick={load} title="Refresh"><RefreshCw size={16}/></button><span className="live">● Live</span></div></header>
  {error&&<div className="alert"><AlertTriangle size={16}/>{error}</div>}{accepted&&<div className="success"><CheckCircle2 size={16}/> Walk-in accepted and added to the live schedule.</div>}
  <div className="kpis"><K icon={<CalendarDays/>} v={d.appointments.length} t="Visible appointments"/><K icon={<Users/>} v={d.stylists.length} t="Active stylists"/><K icon={<Users/>} v={d.customerCount} t="Customers"/><K icon={<Activity/>} v="READY" t="Decision engine"/></div>
  <div className="grid"><section className="panel schedule"><div className="panelhead"><div><small>LIVE SCHEDULE</small><h2>Today at a glance</h2></div><span>{d.appointments.length} entries</span></div>{d.appointments.length?d.appointments.map((a:any)=><div className="appt" key={a.id}><time>{new Date(a.scheduled_start).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</time><div><b>{a.customer||'Guest'}</b><span>{a.service} · {a.stylist}</span></div><label className={a.status==='CONFIRMED'?'confirmed':''}>{a.status}</label></div>):<div className="empty"><CalendarDays size={22}/><b>No appointments in the visible window</b><span>Your salon is quiet. That is a good time to accept a walk-in.</span></div>}</section>
  <section className="panel engine"><small>WALK-IN DECISION ENGINE</small><h2>Should we say yes?</h2><p className="enginecopy">Model the consequence of accepting a walk-in against the current schedule. The engine is deterministic and explainable.</p><select value={svc} onChange={e=>{setSvc(e.target.value);setDec(null);setCandidates([])}}><option value="">Choose a service…</option>{d.services.map((s:any)=><option key={s.id} value={s.id}>{s.name} · {s.duration_min} min · ₹{s.price_inr.toLocaleString('en-IN')}</option>)}</select>{selected&&<div className="servicehint"><span>{selected.duration_min} min service</span><span>₹{selected.price_inr.toLocaleString('en-IN')}</span><span>{selected.buffer_min} min buffer</span></div>}<button className="primary wide" disabled={!svc||busy} onClick={sim}>{busy?'Analyzing live schedule…':'Run decision simulation'} <Sparkles size={16}/></button>
  {dec&&<div className={`result ${dec.state.toLowerCase()}`}><div className="rstate"><strong>{statusIcon}{dec.state.replaceAll('_',' ')}</strong><span>{dec.reason}</span></div><div className="rm"><Metric v={`₹${dec.revenue.toLocaleString('en-IN')}`} t="Revenue"/><Metric v={`${Math.round(dec.maxDelay)} min`} t="Max delay"/><Metric v={`${Math.round(dec.wait)} min`} t="Customer wait"/></div><div className="impact"><span><b>{dec.affected}</b> appointments affected</span><span><b>{Math.round(dec.totalDelay)}</b> total delay minutes</span></div>{dec.state!=='RESCHEDULE'&&<button className="darkbtn wide" disabled={busy} onClick={accept}>Accept this walk-in <ChevronRight size={16}/></button>}</div>}
  {candidates.length>1&&<div className="alternatives"><small>OTHER SAFE PLACEMENTS</small>{candidates.slice(1,4).map((c,i)=><div key={i}><span>{c.state.replaceAll('_',' ')}</span><b>{new Date(c.start).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</b><em>{Math.round(c.maxDelay)}m delay</em></div>)}</div>}
  </section></div>
 </section></main>}
function K({icon,v,t}:{icon:React.ReactNode,v:string|number,t:string}){return <div className="kpi"><div>{icon}</div><b>{v}</b><span>{t}</span></div>}
function Metric({v,t}:{v:string,t:string}){return <b>{v}<small>{t}</small></b>}
